### ISSUE TITLE
Undo changes to plan()

### ISSUE THREAD

**Issue by HenrikBengtsson** [djbetancourt-gh/funGp#14]
Hi. To avoid surprising users who have registered another **future** backends for other purposes before calling your functions, please consider undoing your settings before returning, to avoid breaking their setup.  This can be done by updating:

```r
plan(cluster, workers = par.clust)
```

to

```r
oplan <- plan(cluster, workers = par.clust)
on.exit(plan(oplan), add = TRUE)
```

This is documented in Section 'For package developers' of [`?future::plan`](https://future.futureverse.org/reference/plan.html).

**Comment by djbetancourt-gh** [comment]
Resolved in 0aa6ed6a2a806428533359e8aa9dcaee7bfdde4b
